name: Terraform Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_apply:
    name: Terraform Apply
    uses: soat-tech-challenge/github-workflows/.github/workflows/terraform-apply.yml@main
    secrets: inherit
    with:
      cloud_workspace: ${{ vars.TF_WORKSPACE }}
