name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    uses: soat-tech-challenge/github-workflows/.github/workflows/terraform-destroy.yml@main
    secrets: inherit
    with:
      cloud_workspace: ${{ vars.TF_WORKSPACE }}
